
stages:
  - buildStatic
  - testStatic 
variables:

before_script:


#alpine
#
buildStatic:
  tags: 
    - docker
  image: svirlyu/sscocaller_nsb
  stage: buildStatic
  script:
    - /usr/local/bin/nsb -s sgcocaller.nim -n sgcocaller.nimble -o . -- --d:release --threads:on
    - ls -l .
  artifacts:
    paths:
      - ./sgcocaller

testUbuntu:
  tags:
    - docker
  image: ubuntu
  stage: testStatic
  script:
    - ./sgcocaller -h

testDebian:
  tags:
    - docker
  image: debian
  stage: testStatic
  script:
    - ./sgcocaller -h

testRedHat:
  stage: testStatic
  script:
    - ./sgcocaller -h


## shell executer    
##testFunction:
##  stage: testStatic
##  script:
##    - sh tests/test.sh

testAlpine:
  tags:
    - docker
  image: alpine
  stage: testStatic
  script:
  - ./sgcocaller -h




#release:
#i  tag_name: $CI_COMMIT_TAG
#  script:
#    -  echo "create static build"
#  image: registry.gitlab.com/gitlab-org/release-cli:latest


